import type { Product, Order } from '@ecommerce/types';

export const ADMIN_MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Artisan Leather Wallet',
    slug: 'artisan-leather-wallet',
    description: 'Full-grain leather bifold wallet',
    sku: 'LW-001',
    price: 8999,
    compareAtPrice: 12000,
    currency: 'USD',
    images: [{ id: 'img-1', url: 'https://picsum.photos/seed/wallet/400/400', altText: 'Wallet', position: 0 }],
    categories: [{ id: 'cat-1', name: 'Accessories', slug: 'accessories' }],
    tags: ['leather', 'wallet'],
    variants: [],
    inventoryQuantity: 45,
    status: 'published',
    weight: 0.1,
    metadata: {},
    createdAt: '2024-11-15T10:00:00Z',
    updatedAt: '2024-12-01T10:00:00Z',
  },
  {
    id: 'prod-2',
    name: 'Merino Wool Sweater',
    slug: 'merino-wool-sweater',
    description: 'Superfine merino wool, naturally breathable',
    sku: 'MW-002',
    price: 14999,
    compareAtPrice: 19900,
    currency: 'USD',
    images: [{ id: 'img-2', url: 'https://picsum.photos/seed/sweater/400/400', altText: 'Sweater', position: 0 }],
    categories: [{ id: 'cat-2', name: 'Clothing', slug: 'clothing' }],
    tags: ['wool', 'sweater'],
    variants: [],
    inventoryQuantity: 8,
    status: 'published',
    weight: 0.5,
    metadata: {},
    createdAt: '2024-10-20T10:00:00Z',
    updatedAt: '2024-11-10T10:00:00Z',
  },
  {
    id: 'prod-3',
    name: 'Bamboo Cutting Board Set',
    slug: 'bamboo-cutting-board-set',
    description: 'Sustainable bamboo, 3-piece set',
    sku: 'BB-003',
    price: 6499,
    currency: 'USD',
    images: [{ id: 'img-3', url: 'https://picsum.photos/seed/bamboo/400/400', altText: 'Board', position: 0 }],
    categories: [{ id: 'cat-3', name: 'Kitchen', slug: 'kitchen' }],
    tags: ['bamboo', 'kitchen'],
    variants: [],
    inventoryQuantity: 32,
    status: 'published',
    weight: 1.2,
    metadata: {},
    createdAt: '2024-09-05T10:00:00Z',
    updatedAt: '2024-10-01T10:00:00Z',
  },
  {
    id: 'prod-4',
    name: 'Canvas Tote Bag',
    slug: 'canvas-tote-bag',
    description: 'Heavy-duty organic canvas, reinforced handles',
    sku: 'CT-004',
    price: 3999,
    compareAtPrice: 5500,
    currency: 'USD',
    images: [{ id: 'img-4', url: 'https://picsum.photos/seed/tote/400/400', altText: 'Tote', position: 0 }],
    categories: [{ id: 'cat-1', name: 'Accessories', slug: 'accessories' }],
    tags: ['canvas', 'bag'],
    variants: [],
    inventoryQuantity: 0,
    status: 'draft',
    weight: 0.4,
    metadata: {},
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2024-12-05T10:00:00Z',
  },
  {
    id: 'prod-5',
    name: 'Scented Soy Candle',
    slug: 'scented-soy-candle',
    description: 'Hand-poured soy wax, cedar & amber scent',
    sku: 'SC-005',
    price: 3499,
    currency: 'USD',
    images: [{ id: 'img-5', url: 'https://picsum.photos/seed/candle/400/400', altText: 'Candle', position: 0 }],
    categories: [{ id: 'cat-4', name: 'Home', slug: 'home' }],
    tags: ['candle', 'home'],
    variants: [],
    inventoryQuantity: 67,
    status: 'published',
    weight: 0.3,
    metadata: {},
    createdAt: '2024-08-12T10:00:00Z',
    updatedAt: '2024-09-20T10:00:00Z',
  },
  {
    id: 'prod-6',
    name: 'Ceramic Pour-Over Set',
    slug: 'ceramic-pour-over-set',
    description: 'Handcrafted ceramic dripper + carafe',
    sku: 'CP-006',
    price: 7999,
    compareAtPrice: 9500,
    currency: 'USD',
    images: [{ id: 'img-6', url: 'https://picsum.photos/seed/ceramic/400/400', altText: 'Pour-over', position: 0 }],
    categories: [{ id: 'cat-3', name: 'Kitchen', slug: 'kitchen' }],
    tags: ['ceramic', 'coffee'],
    variants: [],
    inventoryQuantity: 14,
    status: 'published',
    weight: 0.8,
    metadata: {},
    createdAt: '2024-07-22T10:00:00Z',
    updatedAt: '2024-08-15T10:00:00Z',
  },
];

export const ADMIN_MOCK_ORDERS: Order[] = [
  {
    id: 'ord-a1b2c3',
    displayId: 'ORD-1001',
    userId: 'cust-1',
    status: 'delivered',
    total: 12850,
    subtotal: 11850,
    taxTotal: 1000,
    shippingTotal: 0,
    discountTotal: 0,
    currency: 'USD',
    items: [
      { id: 'item-1', productId: 'prod-1', variantId: 'v1', productName: 'Artisan Leather Wallet', variantTitle: 'Default', sku: 'LW-001', unitPrice: 8999, quantity: 1, totalPrice: 8999, imageUrl: 'https://picsum.photos/seed/wallet/80/80' },
      { id: 'item-2', productId: 'prod-5', variantId: 'v5', productName: 'Scented Soy Candle', variantTitle: 'Cedar & Amber', sku: 'SC-005', unitPrice: 3499, quantity: 1, totalPrice: 3499, imageUrl: 'https://picsum.photos/seed/candle/80/80' },
    ],
    shippingAddress: { firstName: 'Alice', lastName: 'Johnson', address1: '123 Main St', city: 'New York', state: 'NY', postalCode: '10001', country: 'US', phone: '555-0101' },
    billingAddress: { firstName: 'Alice', lastName: 'Johnson', address1: '123 Main St', city: 'New York', state: 'NY', postalCode: '10001', country: 'US', phone: '555-0101' },
    paymentStatus: 'captured',
    fulfillmentStatus: 'fulfilled',
    createdAt: '2025-04-20T14:30:00Z',
    updatedAt: '2025-04-25T10:00:00Z',
  },
  {
    id: 'ord-d4e5f6',
    displayId: 'ORD-1002',
    userId: 'cust-2',
    status: 'processing',
    total: 22998,
    subtotal: 21498,
    taxTotal: 1500,
    shippingTotal: 0,
    discountTotal: 0,
    currency: 'USD',
    items: [
      { id: 'item-3', productId: 'prod-2', variantId: 'v2', productName: 'Merino Wool Sweater', variantTitle: 'Medium / Navy', sku: 'MW-002', unitPrice: 14999, quantity: 1, totalPrice: 14999, imageUrl: 'https://picsum.photos/seed/sweater/80/80' },
      { id: 'item-4', productId: 'prod-6', variantId: 'v6', productName: 'Ceramic Pour-Over Set', variantTitle: 'Default', sku: 'CP-006', unitPrice: 7999, quantity: 1, totalPrice: 7999, imageUrl: 'https://picsum.photos/seed/ceramic/80/80' },
    ],
    shippingAddress: { firstName: 'Bob', lastName: 'Smith', address1: '456 Oak Ave', city: 'Los Angeles', state: 'CA', postalCode: '90001', country: 'US', phone: '555-0102' },
    billingAddress: { firstName: 'Bob', lastName: 'Smith', address1: '456 Oak Ave', city: 'Los Angeles', state: 'CA', postalCode: '90001', country: 'US', phone: '555-0102' },
    paymentStatus: 'captured',
    fulfillmentStatus: 'not_fulfilled',
    createdAt: '2025-05-01T09:15:00Z',
    updatedAt: '2025-05-01T09:15:00Z',
  },
  {
    id: 'ord-g7h8i9',
    displayId: 'ORD-1003',
    userId: 'cust-3',
    status: 'pending',
    total: 23000,
    subtotal: 21500,
    taxTotal: 1500,
    shippingTotal: 0,
    discountTotal: 0,
    currency: 'USD',
    items: [
      { id: 'item-5', productId: 'prod-3', variantId: 'v3', productName: 'Bamboo Cutting Board Set', variantTitle: 'Default', sku: 'BB-003', unitPrice: 6499, quantity: 1, totalPrice: 6499, imageUrl: 'https://picsum.photos/seed/bamboo/80/80' },
      { id: 'item-6', productId: 'prod-2', variantId: 'v2', productName: 'Merino Wool Sweater', variantTitle: 'Large / Forest', sku: 'MW-002', unitPrice: 14999, quantity: 1, totalPrice: 14999, imageUrl: 'https://picsum.photos/seed/sweater/80/80' },
    ],
    shippingAddress: { firstName: 'Carol', lastName: 'White', address1: '789 Pine Rd', city: 'Chicago', state: 'IL', postalCode: '60601', country: 'US', phone: '555-0103' },
    billingAddress: { firstName: 'Carol', lastName: 'White', address1: '789 Pine Rd', city: 'Chicago', state: 'IL', postalCode: '60601', country: 'US', phone: '555-0103' },
    paymentStatus: 'pending',
    fulfillmentStatus: 'not_fulfilled',
    createdAt: '2025-05-05T16:45:00Z',
    updatedAt: '2025-05-05T16:45:00Z',
  },
  {
    id: 'ord-j1k2l3',
    displayId: 'ORD-1004',
    userId: 'cust-4',
    status: 'shipped',
    total: 8998,
    subtotal: 8498,
    taxTotal: 500,
    shippingTotal: 0,
    discountTotal: 0,
    currency: 'USD',
    items: [
      { id: 'item-7', productId: 'prod-4', variantId: 'v4', productName: 'Canvas Tote Bag', variantTitle: 'Natural', sku: 'CT-004', unitPrice: 3999, quantity: 1, totalPrice: 3999, imageUrl: 'https://picsum.photos/seed/tote/80/80' },
      { id: 'item-8', productId: 'prod-5', variantId: 'v5', productName: 'Scented Soy Candle', variantTitle: 'Vanilla & Sandalwood', sku: 'SC-005', unitPrice: 3499, quantity: 1, totalPrice: 3499, imageUrl: 'https://picsum.photos/seed/candle/80/80' },
    ],
    shippingAddress: { firstName: 'Dave', lastName: 'Brown', address1: '321 Elm St', city: 'Houston', state: 'TX', postalCode: '77001', country: 'US', phone: '555-0104' },
    billingAddress: { firstName: 'Dave', lastName: 'Brown', address1: '321 Elm St', city: 'Houston', state: 'TX', postalCode: '77001', country: 'US', phone: '555-0104' },
    paymentStatus: 'captured',
    fulfillmentStatus: 'partially_fulfilled',
    createdAt: '2025-04-28T11:20:00Z',
    updatedAt: '2025-05-02T08:00:00Z',
  },
  {
    id: 'ord-m4n5o6',
    displayId: 'ORD-1005',
    userId: 'cust-5',
    status: 'confirmed',
    total: 18598,
    subtotal: 16998,
    taxTotal: 1600,
    shippingTotal: 0,
    discountTotal: 0,
    currency: 'USD',
    items: [
      { id: 'item-9', productId: 'prod-6', variantId: 'v6', productName: 'Ceramic Pour-Over Set', variantTitle: 'Default', sku: 'CP-006', unitPrice: 7999, quantity: 1, totalPrice: 7999, imageUrl: 'https://picsum.photos/seed/ceramic/80/80' },
      { id: 'item-10', productId: 'prod-1', variantId: 'v1', productName: 'Artisan Leather Wallet', variantTitle: 'Brown', sku: 'LW-001', unitPrice: 8999, quantity: 1, totalPrice: 8999, imageUrl: 'https://picsum.photos/seed/wallet/80/80' },
    ],
    shippingAddress: { firstName: 'Eve', lastName: 'Davis', address1: '654 Maple Dr', city: 'Phoenix', state: 'AZ', postalCode: '85001', country: 'US', phone: '555-0105' },
    billingAddress: { firstName: 'Eve', lastName: 'Davis', address1: '654 Maple Dr', city: 'Phoenix', state: 'AZ', postalCode: '85001', country: 'US', phone: '555-0105' },
    paymentStatus: 'captured',
    fulfillmentStatus: 'not_fulfilled',
    createdAt: '2025-05-03T13:00:00Z',
    updatedAt: '2025-05-03T14:00:00Z',
  },
];

export const ADMIN_MOCK_USERS = [
  { id: 'cust-1', firstName: 'Alice', lastName: 'Johnson', email: 'alice@example.com', role: 'customer', createdAt: '2024-09-15T10:00:00Z' },
  { id: 'cust-2', firstName: 'Bob', lastName: 'Smith', email: 'bob@example.com', role: 'customer', createdAt: '2024-10-20T10:00:00Z' },
  { id: 'cust-3', firstName: 'Carol', lastName: 'White', email: 'carol@example.com', role: 'customer', createdAt: '2024-11-05T10:00:00Z' },
  { id: 'cust-4', firstName: 'Dave', lastName: 'Brown', email: 'dave@example.com', role: 'customer', createdAt: '2024-12-10T10:00:00Z' },
  { id: 'cust-5', firstName: 'Eve', lastName: 'Davis', email: 'eve@example.com', role: 'customer', createdAt: '2025-01-20T10:00:00Z' },
  { id: 'admin-1', firstName: 'Admin', lastName: 'User', email: 'admin@yourbrand.com', role: 'admin', createdAt: '2024-08-01T10:00:00Z' },
  { id: 'cust-6', firstName: 'Frank', lastName: 'Miller', email: 'frank@example.com', role: 'customer', createdAt: '2025-02-14T10:00:00Z' },
  { id: 'cust-7', firstName: 'Grace', lastName: 'Lee', email: 'grace@example.com', role: 'customer', createdAt: '2025-03-08T10:00:00Z' },
];
